#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Articulo
	{
		private int id_articulo;
		public virtual int Id_articulo
		{
			get
			{
				return this.id_articulo;
			}
			set
			{
				this.id_articulo = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private double? precio;
		public virtual double? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private string observacion;
		public virtual string Observacion
		{
			get
			{
				return this.observacion;
			}
			set
			{
				this.observacion = value;
			}
		}
		
		private int? rubro;
		public virtual int? Rubro
		{
			get
			{
				return this.rubro;
			}
			set
			{
				this.rubro = value;
			}
		}
		
		private int? subrubro;
		public virtual int? Subrubro
		{
			get
			{
				return this.subrubro;
			}
			set
			{
				this.subrubro = value;
			}
		}
		
		private Rubro rubro1;
		public virtual Rubro Rubro1
		{
			get
			{
				return this.rubro1;
			}
			set
			{
				this.rubro1 = value;
			}
		}
		
		private Subrubro subrubro1;
		public virtual Subrubro Subrubro1
		{
			get
			{
				return this.subrubro1;
			}
			set
			{
				this.subrubro1 = value;
			}
		}
		
		private IList<LineaOrden> lineaOrden = new List<LineaOrden>();
		public virtual IList<LineaOrden> LineaOrden
		{
			get
			{
				return this.lineaOrden;
			}
		}
		
	}
}
#pragma warning restore 1591
