#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Comida
	{
		private int idComida;
		public virtual int IdComida
		{
			get
			{
				return this.idComida;
			}
			set
			{
				this.idComida = value;
			}
		}
		
		private int? tipoComida;
		public virtual int? TipoComida
		{
			get
			{
				return this.tipoComida;
			}
			set
			{
				this.tipoComida = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int? precio;
		public virtual int? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private string ingredientes;
		public virtual string Ingredientes
		{
			get
			{
				return this.ingredientes;
			}
			set
			{
				this.ingredientes = value;
			}
		}
		
		private string observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this.observaciones;
			}
			set
			{
				this.observaciones = value;
			}
		}
		
		private TipoComida tipoComida1;
		public virtual TipoComida TipoComida1
		{
			get
			{
				return this.tipoComida1;
			}
			set
			{
				this.tipoComida1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
