#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class DetalleOrden
	{
		private int id_detalleOrden;
		public virtual int Id_detalleOrden
		{
			get
			{
				return this.id_detalleOrden;
			}
			set
			{
				this.id_detalleOrden = value;
			}
		}
		
		private int id_lineaOrden;
		public virtual int Id_lineaOrden
		{
			get
			{
				return this.id_lineaOrden;
			}
			set
			{
				this.id_lineaOrden = value;
			}
		}
		
		private LineaOrden lineaOrden;
		public virtual LineaOrden LineaOrden
		{
			get
			{
				return this.lineaOrden;
			}
			set
			{
				this.lineaOrden = value;
			}
		}
		
		private IList<Orden> orden = new List<Orden>();
		public virtual IList<Orden> Orden
		{
			get
			{
				return this.orden;
			}
		}
		
	}
}
#pragma warning restore 1591
