#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class LineaOrden
	{
		private int id_lineaOrden;
		public virtual int Id_lineaOrden
		{
			get
			{
				return this.id_lineaOrden;
			}
			set
			{
				this.id_lineaOrden = value;
			}
		}
		
		private int? id_articulo;
		public virtual int? Id_articulo
		{
			get
			{
				return this.id_articulo;
			}
			set
			{
				this.id_articulo = value;
			}
		}
		
		private int? id_cantidad;
		public virtual int? Id_cantidad
		{
			get
			{
				return this.id_cantidad;
			}
			set
			{
				this.id_cantidad = value;
			}
		}
		
		private Articulo articulo;
		public virtual Articulo Articulo
		{
			get
			{
				return this.articulo;
			}
			set
			{
				this.articulo = value;
			}
		}
		
		private IList<DetalleOrden> detalleOrden = new List<DetalleOrden>();
		public virtual IList<DetalleOrden> DetalleOrden
		{
			get
			{
				return this.detalleOrden;
			}
		}
		
	}
}
#pragma warning restore 1591
